[build]
  base    = "HYBRID PLANNER"   # bo Twój projekt siedzi w tym podfolderze
  publish = "."
  command = ""

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory    = "netlify/functions"  # małe litery!
  node_bundler = "esbuild"