[build]
  # Cały build wykonujemy wewnątrz folderu "HYBRID PLANNER"
  base    = "HYBRID PLANNER"
  publish = "."
  command = ""

[functions]
  # Ścieżka LICZONA od "base" => "HYBRID PLANNER/netlify/functions"
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["exceljs"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
